import { StyleSheet } from 'react-native';

export const getStyles = (theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme.colors.primary,
    height: 60,
    paddingHorizontal: 8,
  },
  backButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  headerTitle: {
    color: theme.colors.textInverse,
    fontSize: 20,
    fontWeight: '700',
    flex: 1,
    textAlign: 'center',
    marginHorizontal: 0,
  },
  headerSpacer: {
    width: 48,
    height: 48,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyTitle: {
    fontSize: 16,
    color: theme.colors.textSecondary,
    fontFamily: 'Inter-Medium',
    marginTop: 12,
  },
  filterContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  filterTab: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeFilterTab: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  filterTabText: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    fontFamily: 'Inter-SemiBold',
  },
  activeFilterTabText: {
    color: '#FFFFFF',
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  tenantName: {
    fontSize: 16,
    fontFamily: 'Inter-Bold',
    color: theme.colors.text,
  },
  dateText: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    fontFamily: 'Inter-Regular',
    marginTop: 4,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusText: {
    fontSize: 10,
    fontFamily: 'Inter-Bold',
    textTransform: 'uppercase',
  },
  detailsSection: {
    backgroundColor: theme.isDark ? '#1F2937' : '#F9FAFB',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  detailLabel: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    fontFamily: 'Inter-Medium',
  },
  detailValue: {
    fontSize: 13,
    color: theme.colors.text,
    fontFamily: 'Inter-SemiBold',
  },
  reasonText: {
    fontSize: 13,
    color: theme.colors.text,
    fontFamily: 'Inter-Regular',
    marginTop: 4,
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  approveButton: {
    backgroundColor: theme.colors.primary,
  },
  rejectButton: {
    backgroundColor: '#FEE2E2',
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'Inter-SemiBold',
  },
  actionButtonTextDark: {
    color: '#991B1B',
    fontSize: 14,
    fontFamily: 'Inter-SemiBold',
  },
  inputGroup: {
    marginTop: 12,
  },
  label: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    fontFamily: 'Inter-SemiBold',
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  input: {
    backgroundColor: theme.colors.background,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 8,
    padding: 12,
    color: theme.colors.text,
    fontFamily: 'Inter-Regular',
    fontSize: 14,
  },
  prorationCard: {
    backgroundColor: theme.isDark ? '#1E3A8A' : '#EFF6FF',
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
    borderWidth: 1,
    borderColor: theme.isDark ? '#1E40AF' : '#BFDBFE',
  },
  prorationTitle: {
    fontSize: 10,
    color: theme.isDark ? '#93C5FD' : '#1E40AF',
    fontFamily: 'Inter-Bold',
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  prorationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  prorationLabel: {
    fontSize: 12,
    color: theme.isDark ? '#93C5FD' : '#3B82F6',
    fontFamily: 'Inter-Regular',
  },
  prorationValue: {
    fontSize: 12,
    color: theme.isDark ? '#DBEAFE' : '#1D4ED8',
    fontFamily: 'Inter-SemiBold',
  },
  prorationDivider: {
    height: 1,
    backgroundColor: theme.isDark ? '#1E40AF' : '#BFDBFE',
    marginVertical: 8,
  },
  confirmButton: {
    backgroundColor: '#16a34a',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 12,
  },
  cancelButton: {
    backgroundColor: 'transparent',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    padding: 12,
  },
  modalContainer: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
    maxHeight: '88%',
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  modalTitle: {
    fontSize: 16,
    color: theme.colors.text,
    fontFamily: 'Inter-Bold',
  },
  modalCloseButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.background,
  },
  modalBody: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
});
