import { StyleSheet, Platform, StatusBar } from 'react-native';

export const getStyles = (theme) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 24) + 16 : 16,
    paddingBottom: 0,
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: 24,
    paddingTop: 24,
    paddingHorizontal: 24,
    paddingBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: theme.isDark ? 0.3 : 0.1,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: theme.isDark ? 1 : 0,
    borderColor: theme.colors.border
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 40,
    marginTop: 40,
  },
  logoFull: {
    width: 200,
    height: 80,
  },
  dismissButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 8,
    marginBottom: 8,
  },
  dismissButtonText: {
    color: theme.colors.textSecondary,
    fontSize: 14,
    fontWeight: '500',
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logo: {
    width: 90,
    height: 90,
  },
  logoTextContainer: {
    marginLeft: -20,
  },
  logoTextGreen: {
    fontSize: 26,
    fontWeight: 'bold',
    color: theme.colors.primary,
    letterSpacing: -0.5,
  },
  logoTextGray: {
    fontSize: 26,
    fontWeight: 'bold',
    color: theme.colors.textTertiary,
    letterSpacing: -0.5,
    marginTop: -5,
    marginLeft: -10,
  },

  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  backButtonText: {
    color: theme.colors.primary,
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  header: {
    alignItems: 'center',
    marginBottom: 15,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: theme.colors.primary,
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 14,
    color: theme.colors.textSecondary,
  },

  roleButtons: {
    flexDirection: 'row',
    gap: 16,
  },
  roleButton: {
    flex: 1,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: theme.colors.border,
    alignItems: 'center',
  },
  roleButtonActive: {
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.backgroundSecondary,
  },
  roleButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.textSecondary,
  },
  roleButtonTextActive: {
    color: theme.colors.primary,
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: theme.isDark ? theme.colors.errorLight : '#FEF2F2',
    borderWidth: 1,
    borderColor: theme.colors.error,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    gap: 8,
  },
  errorText: {
    flex: 1,
    fontSize: 14,
    color: theme.isDark ? theme.colors.text : '#991B1B',
  },
  inlineErrorText: {
    fontSize: 12,
    color: theme.colors.error,
    marginTop: -10,
    marginBottom: 8,
    paddingHorizontal: 5,
  },
  form: {
    gap: 16,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 12,
    paddingHorizontal: 16,
    backgroundColor: theme.colors.background,
  },
  inputIcon: {
    marginRight: 8,
  },
  input: {
    flex: 1,
    paddingVertical: 16,
    fontSize: 16,
    color: theme.colors.text,
  },
  eyeIcon: {
    padding: 8,
  },
  forgotPassword: {
    alignSelf: 'flex-end',
  },
  forgotPasswordText: {
    fontSize: 14,
    color: theme.colors.text,
    fontWeight: '500',
    opacity: 0.5,
  },

  termsContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
    paddingHorizontal: 8,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: theme.colors.border,
    marginRight: 16,
    marginTop: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  termsText: {
    flex: 1,
    fontSize: 13,
    color: theme.colors.textSecondary,
    lineHeight: 20,
    opacity: 0.8,
  },
  termsLink: {
    color: theme.colors.primary,
    fontWeight: '600',
  },

  submitButton: {
    backgroundColor: theme.colors.primary,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  submitButtonText: {
    color: theme.colors.textInverse,
    fontSize: 16,
    fontWeight: '600',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 16,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: theme.colors.border,
  },
  dividerText: {
    marginHorizontal: 16,
    fontSize: 14,
    color: theme.colors.textTertiary,
  },
  socialButtons: {
    gap: 16,
  },
  socialButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: theme.colors.border,
    borderRadius: 12,
    paddingVertical: 16,
    gap: 16,
  },
  socialButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: theme.colors.text,
  },
  toggleContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 15,
    marginBottom: 15,
  },
  toggleText: {
    fontSize: 14,
    color: theme.colors.textSecondary,
  },
  toggleLink: {
    fontSize: 14,
    color: theme.colors.primary,
    fontWeight: '600',
  },
  guestOptionContainer: {
    marginTop: 8,
    alignItems: 'center',
    marginBottom: 5,
  },
  guestButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: theme.colors.primary,
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 24,
    gap: 8,
    backgroundColor: theme.colors.backgroundSecondary,
  },
  guestButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  guestHintText: {
    fontSize: 12,
    color: theme.colors.textTertiary,
    marginTop: 8,
    marginBottom: 0,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    backgroundColor: theme.colors.surface,
    borderRadius: 20,
    padding: 25,
    width: '85%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    borderWidth: theme.isDark ? 1 : 0,
    borderColor: theme.colors.border,
  },
  modalIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.colors.text,
    marginBottom: 8,
    textAlign: 'center',
  },
  modalDescription: {
    fontSize: 15,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
  },
  reasonContainer: {
    borderLeftWidth: 4,
    borderLeftColor: theme.colors.error,
    padding: 16,
    borderRadius: 8,
    marginBottom: 25,
    width: '100%',
  },
  reasonLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  reasonText: {
    fontSize: 14,
    fontStyle: 'italic',
  },
  modalActions: {
    width: '100%',
    gap: 8,
  },
  resubmitButton: {
    backgroundColor: theme.colors.error,
    paddingVertical: 16,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  resubmitButtonText: {
    color: theme.colors.textInverse,
    fontWeight: 'bold',
    fontSize: 16,
  },
  modalCloseButton: {
    paddingVertical: 16,
    borderRadius: 12,
    width: '100%',
  },
  modalCloseButtonText: {
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
  },
  fullScreenModal: {
    flex: 1,
    backgroundColor: theme.colors.background,
    padding: 16,
    paddingTop: 60,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  fullModalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: theme.colors.primary,
  },
  modalScroll: {
    paddingBottom: 16,
  },
  idTypeContainer: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 10,
    marginBottom: 24,
    overflow: 'hidden',
  },
  idTypeScroll: {
    padding: 8,
  },
  idTypeBadge: {
    padding: 8,
    borderRadius: 8,
    marginRight: 8,
  },
  idTypeBadgeText: {
    fontWeight: '500',
  },
  uploadButton: {
    height: 120,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  uploadButtonText: {
    marginTop: 8,
  },
  uploadPreview: {
    width: '100%',
    height: '100%',
    borderRadius: 10,
  },
  submitButtonRe: {
    backgroundColor: theme.colors.primary,
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
  },
  submitButtonTextRe: {
    fontWeight: 'bold',
    fontSize: 18,
  },
  emailAvailabilityText: {
    fontSize: 12,
    marginTop: -10,
    marginBottom: 8,
    paddingHorizontal: 5,
  },
  passwordChecksContainer: {
    marginTop: 8,
    paddingHorizontal: 5,
    marginBottom: 8,
  },
  passwordCheckItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  passwordCheckText: {
    marginLeft: 5,
    color: '#9CA3AF',
  },
});

export default getStyles;
