import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    header: {
        backgroundColor: '#00A651',
        paddingHorizontal: 24,
        paddingTop: 40,
        paddingBottom: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    headerIcon: {
        padding: 4,
    },
    headerTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#FFFFFF',
        textAlign: 'center',
        flex: 1,
    },
    menuBackdrop: {
        flex: 1,
    },
    menuDrawer: {
        position: 'absolute',
        left: 0,
        top: 0,
        bottom: 0,
        width: '80%',
        backgroundColor: '#FFFFFF',
        shadowColor: '#000',
        shadowOffset: { width: 2, height: 0 },
        shadowOpacity: 0.25,
        shadowRadius: 10,
        elevation: 30,
        zIndex: 1001,

    },
    menuHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        padding: 20,
        backgroundColor: '#F3F4F6',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    menuUserInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        flex: 1,
    },
    menuAvatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#D1FAE5', // Changed to green tint
        justifyContent: 'center',
        alignItems: 'center',
    },
    menuUserName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#111827',
    },
    menuUserEmail: {
        fontSize: 14,
        color: '#6B7280',
        marginTop: 2,
    },
    menuItems: {
        flex: 1,
        paddingTop: 8,
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        gap: 16,
    },
    menuItemText: {
        flex: 1,
        fontSize: 16,
        color: '#374151',
        fontWeight: '500',
    },
    searchContainer: {
        paddingHorizontal: 20,
        marginTop: 5,
        marginBottom: 24,
    },
    searchBar: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
    },
    searchInput: {
        flex: 1,
        fontSize: 16,
        marginLeft: 12,
        color: '#111827',
    },
    searchButton: {
        backgroundColor: '#00A651',
        paddingHorizontal: 20,
        paddingVertical: 8,
        borderRadius: 12,
    },
    searchButtonText: {
        color: '#FFFFFF',
        fontWeight: '600',
        fontSize: 14,
    },
    tabsContainer: {
        marginBottom: 24,
    },
    tabsContent: {
        paddingHorizontal: 24,
        gap: 12,
    },
    tab: {
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 12,
        marginRight: 12,
    },
    tabActive: {
        backgroundColor: '#00A651',
        shadowColor: '#00A651',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    tabText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#374151',
    },
    tabTextActive: {
        color: '#FFFFFF',
    },
    cardsContainer: {
        paddingHorizontal: 24,
        paddingBottom: 80,
    },
    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
        overflow: 'hidden',
    },
    imageContainer: {
        height: 200,
        position: 'relative',
    },
    image: {
        width: '100%',
        height: '100%',
    },
    likeButton: {
        position: 'absolute',
        top: 16,
        right: 16,
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    cardContent: {
        padding: 16,
    },
    dormName: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#111827',
        marginBottom: 8,
    },
    locationContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    locationText: {
        fontSize: 14,
        color: '#6B7280',
        marginLeft: 6,
    },
    ratingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    ratingBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FEF3C7',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
        marginRight: 8,
    },
    ratingText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#111827',
        marginLeft: 4,
    },
    reviewsText: {
        fontSize: 14,
        color: '#9CA3AF',
    },
    amenitiesContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: 16,
        gap: 8,
    },
    amenityBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#D1FAE5',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
    },
    amenityText: {
        fontSize: 12,
        color: '#00A651',
        marginLeft: 4,
        fontWeight: '500',
    },
    footer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
    },
    price: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#00A651',
    },
    priceLabel: {
        fontSize: 12,
        color: '#9CA3AF',
    },
    viewButton: {
        backgroundColor: '#00A651',
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 12,
    },
    viewButtonText: {
        color: '#FFFFFF',
        fontWeight: '600',
        fontSize: 14,
    },
    loadMoreContainer: {
        paddingHorizontal: 24,
        paddingVertical: 24,
        alignItems: 'center',
        marginBottom: 80,
    },
    loadMoreButton: {
        backgroundColor: '#FFFFFF',
        borderWidth: 2,
        borderColor: '#00A651',
        paddingHorizontal: 32,
        paddingVertical: 12,
        borderRadius: 12,
    },
    loadMoreText: {
        color: '#00A651',
        fontWeight: '600',
        fontSize: 16,
    },
    filterButton: {
        padding: 8,
        backgroundColor: '#F3F4F6',
        borderRadius: 8,
        position: 'relative',
    },
    filterBadge: {
        position: 'absolute',
        top: 6,
        right: 6,
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#4CAF50',
    },
    activeFilterContainer: {
        marginTop: 12,
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    activeFilterChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8F5E9',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        gap: 6,
    },
    activeFilterText: {
        color: '#4CAF50',
        fontSize: 14,
        fontWeight: '600',
    },
    modalOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingBottom: 40,
        maxHeight: '70%',
        zIndex: 1001,

    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#111827',
    },
    filterOptionsContainer: {
        padding: 20,
    },
    filterOption: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
        backgroundColor: '#F9FAFB',
        borderRadius: 12,
        marginBottom: 12,
        borderWidth: 2,
        borderColor: 'transparent',
    },
    filterOptionActive: {
        backgroundColor: '#E8F5E9',
        borderColor: '#4CAF50',
    },
    filterOptionContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    filterOptionText: {
        fontSize: 16,
        color: '#6B7280',
        fontWeight: '500',
    },
    filterOptionTextActive: {
        color: '#4CAF50',
        fontWeight: '600',
    },
    typeBadge: {
        position: 'absolute',
        top: 12,
        left: 12,
        backgroundColor: 'rgba(0, 166, 81, 0.9)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
    },
    typeBadgeText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '600',
    },
    // BOTTOM NAVIGATION STYLES
    bottomNav: {
        flexDirection: 'row',
        backgroundColor: '#4CAF50',
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        paddingVertical: 10,
        paddingBottom: 10,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 8,
        zIndex: 1001,

    },
    navItem: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 8,
    },
    activeIndicator: {
        width: 40,
        height: 3,
        backgroundColor: '#FDD835',
        borderRadius: 2,
        marginTop: 4,
    },
});

export default styles;