import { StyleSheet } from 'react-native';

export const getStyles = (theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      padding: 16,
      paddingBottom: 48,
      gap: 14,
    },
    loadingContent: {
      padding: 16,
      gap: 12,
    },
    greetingSection: {
      backgroundColor: theme.colors.surface,
      borderRadius: 14,
      padding: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    greetingTitle: {
      color: theme.colors.text,
      fontSize: 22,
      fontWeight: '800',
    },
    greetingSubtitle: {
      marginTop: 6,
      color: theme.colors.textSecondary,
      fontSize: 13,
    },
    section: {
      backgroundColor: theme.colors.surface,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 14,
      gap: 10,
      shadowColor: '#000',
      shadowOpacity: theme.isDark ? 0.24 : 0.08,
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 6,
      elevation: 2,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    sectionTitle: {
      color: theme.colors.text,
      fontSize: 17,
      fontWeight: '800',
    },
    sectionHint: {
      color: theme.colors.textTertiary,
      fontSize: 11,
      fontWeight: '600',
    },
    statsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: 10,
    },
    statCard: {
      width: '48.5%',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: 'rgba(0,0,0,0.04)',
      padding: 12,
      minHeight: 112,
      justifyContent: 'space-between',
    },
    statIcon: {
      width: 30,
      height: 30,
      borderRadius: 15,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 6,
    },
    statValue: {
      color: theme.colors.text,
      fontWeight: '800',
      fontSize: 17,
    },
    statLabel: {
      color: theme.colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
      fontWeight: '700',
      fontSize: 10,
      marginTop: 2,
    },
    statSubLabel: {
      color: theme.colors.textTertiary,
      fontSize: 11,
      marginTop: 4,
    },
    panelBody: {
      marginTop: 4,
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
      paddingTop: 8,
      gap: 8,
    },
    panelRow: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 10,
      gap: 4,
      backgroundColor: theme.colors.backgroundSecondary,
    },
    panelPrimary: {
      color: theme.colors.text,
      fontWeight: '700',
      fontSize: 13,
    },
    panelSecondary: {
      color: theme.colors.textSecondary,
      fontSize: 12,
    },
    panelTertiary: {
      color: theme.colors.textTertiary,
      fontSize: 11,
    },
    panelAccent: {
      color: theme.colors.primary,
      fontSize: 12,
      fontWeight: '700',
    },
    panelEmpty: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      paddingVertical: 6,
    },
    progressHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
    },
    progressTrack: {
      width: '100%',
      height: 8,
      borderRadius: 999,
      overflow: 'hidden',
      backgroundColor: theme.colors.border,
      marginTop: 4,
      marginBottom: 2,
    },
    progressFill: {
      height: '100%',
      borderRadius: 999,
      backgroundColor: theme.colors.primary,
    },
    alertCard: {
      borderRadius: 12,
      borderWidth: 1,
      padding: 12,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    alertBody: {
      flex: 1,
    },
    alertTitle: {
      color: theme.colors.text,
      fontWeight: '700',
      fontSize: 13,
    },
    alertText: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      marginTop: 2,
    },
    alertLink: {
      color: theme.colors.primary,
      fontSize: 12,
      fontWeight: '700',
      marginTop: 2,
    },
    emptyCard: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.backgroundSecondary,
      padding: 12,
      gap: 8,
      alignItems: 'flex-start',
    },
    emptyCardText: {
      color: theme.colors.textSecondary,
      fontSize: 12,
    },
    inlineButton: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: theme.colors.primary,
    },
    inlineButtonText: {
      color: theme.colors.textInverse,
      fontWeight: '700',
      fontSize: 12,
    },
    roomCard: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.backgroundSecondary,
      padding: 12,
      gap: 4,
    },
    roomTitle: {
      color: theme.colors.text,
      fontWeight: '700',
      fontSize: 14,
      flex: 1,
    },
    roomPrice: {
      color: theme.colors.primary,
      fontWeight: '700',
      fontSize: 13,
    },
    roomMeta: {
      color: theme.colors.textSecondary,
      fontSize: 12,
    },
    activityRow: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.backgroundSecondary,
      padding: 10,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    activityIconWrap: {
      width: 24,
      height: 24,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.colors.primaryLight,
    },
    activityBody: {
      flex: 1,
      gap: 2,
    },
    activityTitle: {
      color: theme.colors.text,
      fontWeight: '700',
      fontSize: 12,
    },
    activityText: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      lineHeight: 17,
    },
    activityTime: {
      color: theme.colors.textTertiary,
      fontSize: 10,
      marginTop: 2,
    },
    timelineCard: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.backgroundSecondary,
      padding: 12,
      gap: 6,
    },
    timelineMonth: {
      color: theme.colors.text,
      fontWeight: '700',
      fontSize: 13,
      flex: 1,
    },
    timelineAmount: {
      color: theme.colors.warningDark,
      fontWeight: '700',
      fontSize: 12,
    },
    timelineDue: {
      color: theme.colors.textSecondary,
      fontSize: 11,
    },
    timelineRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    timelineDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: theme.colors.primary,
    },
    timelineText: {
      color: theme.colors.textSecondary,
      fontSize: 11,
      flex: 1,
    },
    summaryCard: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.backgroundSecondary,
      padding: 12,
      gap: 10,
    },
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    summaryLabel: {
      color: theme.colors.textSecondary,
      fontSize: 12,
    },
    summaryValue: {
      color: theme.colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    primaryButton: {
      marginTop: 4,
      borderRadius: 10,
      backgroundColor: theme.colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
    },
    primaryButtonText: {
      color: theme.colors.textInverse,
      fontWeight: '700',
      fontSize: 14,
    },
  });

export default getStyles;
