import { StyleSheet } from 'react-native';

export const getStyles = (theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    paddingTop: 35,
    paddingBottom: 16,
    borderBottomWidth: 1,
    backgroundColor: theme.colors.primary,
    borderBottomColor: 'transparent',
  },
  headerSpacer: {
    width: 40,
  },
  headerTextContainer: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.textInverse,
  },
  contentContainer: {
    flex: 1,
  },
  content: {
    flex: 1,
    padding: 16,
    paddingBottom: 24,
    backgroundColor: theme.colors.background,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  spacer: {
    height: 16,
  },
  statCard: {
    flex: 1,
    borderRadius: 12,
    padding: 12,
    marginHorizontal: 6,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: theme.isDark ? 0.3 : 0.08,
    shadowRadius: 4,
    backgroundColor: theme.colors.surface,
  },
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  statValue: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 4,
    color: theme.colors.text,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    color: theme.colors.textSecondary,
  },
  statSubLabel: {
    fontSize: 10,
    marginTop: 2,
    color: theme.colors.textTertiary,
  },
  propertyCard: {
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: theme.isDark ? 0.3 : 0.1,
    shadowRadius: 4,
    backgroundColor: theme.colors.surface,
    borderWidth: theme.isDark ? 1 : 0,
    borderColor: theme.colors.border,
  },
  propertyImage: {
    width: '100%',
    height: 200,
    backgroundColor: theme.colors.backgroundTertiary,
  },
  propertyOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 200,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
    padding: 16,
  },
  propertyTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#fff',
  },
  propertyAddress: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.9)',
    marginTop: 4,
  },
  propertyContent: {
    padding: 16,
  },
  landlordSection: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 0,
    gap: 12,
    backgroundColor: 'transparent',
  },
  landlordAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: theme.colors.backgroundTertiary,
  },
  landlordInfo: {
    flex: 1,
  },
  landlordLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.textTertiary,
  },
  landlordName: {
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 2,
    color: theme.colors.text,
  },
  messageButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
  },
  card: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: theme.isDark ? 0.3 : 0.1,
    shadowRadius: 4,
    backgroundColor: theme.colors.surface,
    borderWidth: theme.isDark ? 1 : 0,
    borderColor: theme.colors.border,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 16,
    color: theme.colors.text,
  },
  paymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  paymentLabel: {
    fontSize: 14,
    color: theme.colors.textSecondary,
  },
  paymentValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.colors.text,
  },
  divider: {
    height: 1,
    marginVertical: 8,
    backgroundColor: theme.colors.border,
  },
  primaryButton: {
    borderRadius: 8,
    padding: 14,
    alignItems: 'center',
    marginTop: 16,
    backgroundColor: theme.colors.primary,
  },
  primaryButtonText: {
    color: theme.colors.textInverse,
    fontSize: 16,
    fontWeight: '600',
  },
  actionButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 14,
    borderRadius: 0,
    marginBottom: 8,
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderBottomWidth: 1,
    borderColor: theme.colors.border,
  },
  actionText: {
    fontSize: 14,
    fontWeight: '500',
    color: theme.colors.text,
  },
  emptyState: {
    borderRadius: 12,
    padding: 32,
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderWidth: theme.isDark ? 1 : 0,
    borderColor: theme.colors.border,
  },
  emptyIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    backgroundColor: theme.colors.backgroundTertiary,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 8,
    color: theme.colors.text,
  },
  emptyText: {
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 20,
    color: theme.colors.textSecondary,
  },
  upcomingCard: {
    borderRadius: 12,
    borderWidth: 1,
    padding: 16,
    marginTop: 24,
    flexDirection: 'row',
    gap: 12,
    backgroundColor: theme.isDark ? theme.colors.brand900 : '#EFF6FF',
    borderColor: theme.isDark ? theme.colors.brand700 : '#BFDBFE',
  },
  upcomingIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: theme.isDark ? theme.colors.brand800 : '#BFDBFE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  upcomingContent: {
    flex: 1,
  },
  upcomingTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.isDark ? theme.colors.brand100 : '#1E3A8A',
    marginBottom: 4,
  },
  upcomingText: {
    fontSize: 13,
    color: theme.isDark ? theme.colors.brand200 : '#1E40AF',
    lineHeight: 18,
  },
  upcomingBold: {
    fontWeight: 'bold',
  },
  upcomingLink: {
    fontSize: 13,
    color: theme.isDark ? theme.colors.brand300 : '#1E40AF',
    fontWeight: '600',
    marginTop: 8,
  },
});

export default getStyles;
